repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.13.0
    hooks:
      - id: terraform-docs-system
        args: ["lambda"]
      - id: terraform-docs-system
        args: ["service-iam-role"]
      - id: terraform-docs-system
        args: ["kinesis-stream"]
      - id: terraform-docs-system
        args: ["api-gateway"]
      - id: terraform-docs-system
        args: ["eks-cluster"]
